name: Build docker image

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  packages: write
  contents: write

jobs:
  build-image:
    name: Build and push docker image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build image'
        run: |
          REPOSITORY_OWNER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          REPOSITORY_NAME="${{ github.event.repository.name }}"
          docker build . --tag ghcr.io/$REPOSITORY_OWNER/$REPOSITORY_NAME:latest
          docker push ghcr.io/$REPOSITORY_OWNER/$REPOSITORY_NAME:latest
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: VeryBigThings/ml-infra
          event-type: update-user-code
